### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by uvlek** [jnhuynh/brick_cloud_firestore#4]
I know that it is alpha, but could you help me with setup. If I use this from doc:
```
brick_cloud_firestore:
  git:
    url: https://github.com/jnhuynh/brick_cloud_firestore.git
    path: packages/brick_cloud_firestore
brick_offline_first: any

dev_dependencies:
  build_runner: any
  brick_offline_first_with_cloud_firestore_build:
    git:
      url: https://github.com/jnhuynh/brick_cloud_firestore.git
      path: packages/brick_offline_first_with_cloud_firestore_build
```
I have several issues.
First one there is not packages folder - i just removed it - passed ok.
Second 
`Error on line 20, column 11: Invalid description in the "brick_offline_first_with_cloud_firestore_build" pubspec on the "brick_cloud_firestore_generator" dependency: "../brick_cloud_firestore_generator" is a relative path, but this isn't a local pubspec.`

Do you have idea how fix it?

**Comment by tshedor** [comment]
@uvlek can you try adding this to your pubspec.yaml until we get this fixed?

```yaml
dependency_overrides:
  brick_cloud_firestore_generator:
    git:
      url: https://github.com/jnhuynh/brick_cloud_firestore.git
      path: brick_cloud_firestore_generator
```
